SELECT car.CAR_ID, car.CAR_TYPE, ROUND(car.DAILY_FEE*(1-(plan.DISCOUNT_RATE/100))*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS history ON car.CAR_ID = history.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS plan ON car.CAR_TYPE = plan.CAR_TYPE
WHERE car.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    WHERE END_DATE > '2022-11-01'
    ) AND plan.DURATION_TYPE = '30일 이상'
GROUP BY car.CAR_ID
HAVING CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE <= 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC