SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS r1
WHERE FAVORITES = (SELECT MAX(r2.FAVORITES)
                    FROM REST_INFO AS r2
                    WHERE r1.FOOD_TYPE = r2.FOOD_TYPE)
ORDER BY 1 DESC