SELECT YEAR(o.sales_date) AS YEAR, MONTH(o.sales_date) AS MONTH, COUNT(DISTINCT o.USER_ID) AS PUCHASED_USERS, ROUND((COUNT(DISTINCT o.USER_ID)/ (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)),1) AS PUCHASED_RATIO
FROM USER_INFO AS u
JOIN ONLINE_SALE AS o ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = '2021'
GROUP BY 1, 2
ORDER BY 1, 2